### ISSUE TITLE
Can't generate enum tables

### ISSUE THREAD

**Issue by TAGC** [SpatialFocus/SpatialFocus.EntityFrameworkCore.Extensions#15]
I've spent two hours trying to get this library to generate enum tables and I can't get it to do anything. Absolutely no idea why; I've tried everything I can think of.

I cloned your demo project, checked out the v2.0.0 commit and was able to get that to work, but haven't been able to make my project work even while making the two as similar as possible.

[Here's what I've tried](https://github.com/TAGC/enum-table-generation-issue). Any idea what's wrong?

### Steps To Reproduce

1. Checkout code
2. Open the package manager console
3. Run `Add-Migration InitialCreate`

Edit: To highlight the parts that are relevant:

### Models

```cs
public class Product
{
    private Product()
    {
    }

    public int Id { get; private set; }

    public CommissionPlan Plan { get; private set; }
}
``` 

```cs
public enum CommissionPlan
{
    NotSet = 0,
    NonPremium,
    Premium,
    MotabilityNonPremium,
    MotabilityPremium
}
```

### Context

```cs
public class CommissionsContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);

        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlite("Data Source=demo.db");
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ConfigureEnumLookup(EnumLookupOptions.Default.Singularize());
        modelBuilder.Entity<Product>();
    }
}
```

### What Gets Generated

```cs
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Product",
            columns: table => new
            {
                Id = table.Column<int>(nullable: false)
                    .Annotation("Sqlite:Autoincrement", true),
                Plan = table.Column<int>(nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Product", x => x.Id);
            });
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Product");
    }
}
```

**Comment by Dresel** [comment]
```csharp
modelBuilder.ConfigureEnumLookup(EnumLookupOptions.Default.Singularize());
modelBuilder.Entity<Product>();
```

If you run `ConfigureEnumLookup` before declaring your entity it won't find anything. `ConfigureEnumLookup` runs immediately so it should be the last thing executed in `OnModelCreating`.

Might be worth adding this to the README.md.

**Comment by TAGC** [comment]
Thanks for the fast response. As well as the README, it might be worth updating the sample as well - it does the call to `ConfigureEnumLookup` before any entity configuration, and seems to "accidentally" work this way presumably because the entity type is exposed as a `DbSet`:

https://github.com/SpatialFocus/EntityFrameworkCore.Extensions/blob/dc2f146aa71ea2bc36166d520b7ebb46f4a8c71e/samples/SpatialFocus.EntityFrameworkCore.Extensions.SQLiteDemo/Data/DemoContext.cs#L41-L49
