### ISSUE TITLE
Exception when using nugget package 2.1.0

### ISSUE THREAD

**Issue by Alexplose** [SpatialFocus/SpatialFocus.EntityFrameworkCore.Extensions#18]
I get this exception when using latest nugget package : 
System.MissingMethodException: 'Method not found: 'System.String Humanizer.InflectorExtensions.Singularize(System.String, Boolean)'.'

From this line : 
modelBuilder.ConfigureEnumLookup(EnumLookupOptions.Default.Singularize().SetNamingScheme(name => "Ref_" + name).UseNumberAsIdentifier().SetDeleteBehavior(DeleteBehavior.ClientSetNull));

I don't know why, when I build from the git repo all tests passes, and the exception isn't thrown.

I had to update to Humanizer 2.8.26, because of another packages, maybe this is the issue.

**Comment by pergerch** [comment]
I cannot reproduce the issue using the included sample project. Do you maybe have a small test repo for us to reproduce?

**Comment by Alexplose** [comment]
I just found that the Singularize signature has changed to  :
public string Singularize(string word, bool inputIsKnownToBePlural = true, **bool skipSimpleWords = false**)
There is a new argument.
The pluralize method didn't change, that's why I don't get any exception when using Pluralize, but Singularize throw an exception.

**Comment by pergerch** [comment]
But it has a default value of __false__ so I don't see why this should be an issue.
Let me create a small test app and have a look

**Comment by pergerch** [comment]
Your assumptions were correct. I updated to the latest Humanizer version and it should work for you now. Nuget v2.1.2 should fix the issue. Thanks for reporting this.
