### ISSUE TITLE
Collection of enums/lookups

### ISSUE THREAD

**Issue by rich0726** [SpatialFocus/SpatialFocus.EntityFrameworkCore.Extensions#21]
I've been tinkering with your EFCore Extensions package.  One question.

Let's say I have a field on my base object, Person, called Sports.  A given person can play multiple sports, and of course, many people can play a sport....classic Many-To-Many.  

So I define an ICollection of Sports in my Person class, and an ICollection of Person(s) in my Sports class, and EFCore 5 predictably created the intermediary JOIN table PersonSports.  All the key relationships are good to go.

I also defined Sports as an enum in my code, and figured out how to seed the default Sports values.  

But. what about weird sports?  Pickleball?  Curling?  Underwater Basket Weaving?

I'm looking for an open enumeration, I know that.  Assuming that I can put non-standard sports into the Sports table, and further assuming that when I make a GET call to my Person object, I want a comma-delimited string of the Sports they play, how would that work?   Will the Extensions package help me?

**Comment by pergerch** [comment]
I am not sure, I am following. Our package helps to seed the enum values into lookup tables, we also created. Similar to the join table in EF Core 5 you mentioned. 
But enum by definition is a set of named constants. What you are looking for is just a regular list of string, I believe?!
