### ISSUE TITLE
Support for .NET 6 / EFCore 6

### ISSUE THREAD

**Issue by bdbvb** [SpatialFocus/SpatialFocus.EntityFrameworkCore.Extensions#23]
I'm using the library for generating enum tables, but it looks like it doesn't work yet with .NET 6 / EFCore 6.

Error example:

 <System.MissingMethodException: Method not found: 'Boolean Microsoft.EntityFrameworkCore.EntityTypeExtensions.IsOwned(Microsoft.EntityFrameworkCore.Metadata.IEntityType)'.
       at SpatialFocus.EntityFrameworkCore.Extensions.EnumLookupExtension.ConfigureEnumLookup(ModelBuilder modelBuilder, EnumLookupOptions enumOptions)
....

**Comment by Dresel** [comment]
See #22.
